/*
 *  Version feature information
 *
 *  Copyright (C) 2006-2015, ARM Limited, All Rights Reserved
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may
 *  not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  This file is part of mbed TLS (https://tls.mbed.org)
 */

#if !defined(JHD_TLS_CONFIG_FILE)
#include <tls/jhd_tls_config.h"
#else
#include JHD_TLS_CONFIG_FILE
#endif

#if defined(JHD_TLS_VERSION_C)

#include <tls/jhd_tls_version.h"

#include <string.h>

static const char *features[] = {
#if defined(JHD_TLS_VERSION_FEATURES)
#if defined(JHD_TLS_HAVE_ASM)
    "JHD_TLS_HAVE_ASM",
#endif /* JHD_TLS_HAVE_ASM */
#if defined(JHD_TLS_NO_UDBL_DIVISION)
    "JHD_TLS_NO_UDBL_DIVISION",
#endif /* JHD_TLS_NO_UDBL_DIVISION */
#if defined(JHD_TLS_HAVE_SSE2)
    "JHD_TLS_HAVE_SSE2",
#endif /* JHD_TLS_HAVE_SSE2 */
#if defined(JHD_TLS_HAVE_TIME)
    "JHD_TLS_HAVE_TIME",
#endif /* JHD_TLS_HAVE_TIME */
#if defined(JHD_TLS_HAVE_TIME_DATE)
    "JHD_TLS_HAVE_TIME_DATE",
#endif /* JHD_TLS_HAVE_TIME_DATE */
#if defined(JHD_TLS_PLATFORM_MEMORY)
    "JHD_TLS_PLATFORM_MEMORY",
#endif /* JHD_TLS_PLATFORM_MEMORY */
#if defined(JHD_TLS_PLATFORM_NO_STD_FUNCTIONS)
    "JHD_TLS_PLATFORM_NO_STD_FUNCTIONS",
#endif /* JHD_TLS_PLATFORM_NO_STD_FUNCTIONS */
#if defined(JHD_TLS_PLATFORM_EXIT_ALT)
    "JHD_TLS_PLATFORM_EXIT_ALT",
#endif /* JHD_TLS_PLATFORM_EXIT_ALT */
#if defined(JHD_TLS_PLATFORM_TIME_ALT)
    "JHD_TLS_PLATFORM_TIME_ALT",
#endif /* JHD_TLS_PLATFORM_TIME_ALT */
#if defined(JHD_TLS_PLATFORM_FPRINTF_ALT)
    "JHD_TLS_PLATFORM_FPRINTF_ALT",
#endif /* JHD_TLS_PLATFORM_FPRINTF_ALT */
#if defined(JHD_TLS_PLATFORM_PRINTF_ALT)
    "JHD_TLS_PLATFORM_PRINTF_ALT",
#endif /* JHD_TLS_PLATFORM_PRINTF_ALT */
#if defined(JHD_TLS_PLATFORM_SNPRINTF_ALT)
    "JHD_TLS_PLATFORM_SNPRINTF_ALT",
#endif /* JHD_TLS_PLATFORM_SNPRINTF_ALT */
#if defined(JHD_TLS_PLATFORM_NV_SEED_ALT)
    "JHD_TLS_PLATFORM_NV_SEED_ALT",
#endif /* JHD_TLS_PLATFORM_NV_SEED_ALT */
#if defined(JHD_TLS_PLATFORM_SETUP_TEARDOWN_ALT)
    "JHD_TLS_PLATFORM_SETUP_TEARDOWN_ALT",
#endif /* JHD_TLS_PLATFORM_SETUP_TEARDOWN_ALT */
#if defined(JHD_TLS_DEPRECATED_WARNING)
    "JHD_TLS_DEPRECATED_WARNING",
#endif /* JHD_TLS_DEPRECATED_WARNING */
#if defined(JHD_TLS_DEPRECATED_REMOVED)
    "JHD_TLS_DEPRECATED_REMOVED",
#endif /* JHD_TLS_DEPRECATED_REMOVED */
#if defined(JHD_TLS_TIMING_ALT)
    "JHD_TLS_TIMING_ALT",
#endif /* JHD_TLS_TIMING_ALT */
#if defined(JHD_TLS_AES_ALT)
    "JHD_TLS_AES_ALT",
#endif /* JHD_TLS_AES_ALT */
#if defined(JHD_TLS_ARC4_ALT)
    "JHD_TLS_ARC4_ALT",
#endif /* JHD_TLS_ARC4_ALT */
#if defined(JHD_TLS_ARIA_ALT)
    "JHD_TLS_ARIA_ALT",
#endif /* JHD_TLS_ARIA_ALT */
#if defined(JHD_TLS_BLOWFISH_ALT)
    "JHD_TLS_BLOWFISH_ALT",
#endif /* JHD_TLS_BLOWFISH_ALT */
#if defined(JHD_TLS_CAMELLIA_ALT)
    "JHD_TLS_CAMELLIA_ALT",
#endif /* JHD_TLS_CAMELLIA_ALT */
#if defined(JHD_TLS_CCM_ALT)
    "JHD_TLS_CCM_ALT",
#endif /* JHD_TLS_CCM_ALT */
#if defined(JHD_TLS_CMAC_ALT)
    "JHD_TLS_CMAC_ALT",
#endif /* JHD_TLS_CMAC_ALT */
#if defined(JHD_TLS_DES_ALT)
    "JHD_TLS_DES_ALT",
#endif /* JHD_TLS_DES_ALT */
#if defined(JHD_TLS_DHM_ALT)
    "JHD_TLS_DHM_ALT",
#endif /* JHD_TLS_DHM_ALT */
#if defined(JHD_TLS_ECJPAKE_ALT)
    "JHD_TLS_ECJPAKE_ALT",
#endif /* JHD_TLS_ECJPAKE_ALT */
#if defined(JHD_TLS_GCM_ALT)
    "JHD_TLS_GCM_ALT",
#endif /* JHD_TLS_GCM_ALT */
#if defined(JHD_TLS_MD2_ALT)
    "JHD_TLS_MD2_ALT",
#endif /* JHD_TLS_MD2_ALT */
#if defined(JHD_TLS_MD4_ALT)
    "JHD_TLS_MD4_ALT",
#endif /* JHD_TLS_MD4_ALT */
#if defined(JHD_TLS_MD5_ALT)
    "JHD_TLS_MD5_ALT",
#endif /* JHD_TLS_MD5_ALT */
#if defined(JHD_TLS_RIPEMD160_ALT)
    "JHD_TLS_RIPEMD160_ALT",
#endif /* JHD_TLS_RIPEMD160_ALT */
#if defined(JHD_TLS_RSA_ALT)
    "JHD_TLS_RSA_ALT",
#endif /* JHD_TLS_RSA_ALT */
#if defined(JHD_TLS_SHA1_ALT)
    "JHD_TLS_SHA1_ALT",
#endif /* JHD_TLS_SHA1_ALT */
#if defined(JHD_TLS_SHA256_ALT)
    "JHD_TLS_SHA256_ALT",
#endif /* JHD_TLS_SHA256_ALT */
#if defined(JHD_TLS_SHA512_ALT)
    "JHD_TLS_SHA512_ALT",
#endif /* JHD_TLS_SHA512_ALT */
#if defined(JHD_TLS_XTEA_ALT)
    "JHD_TLS_XTEA_ALT",
#endif /* JHD_TLS_XTEA_ALT */
#if defined(JHD_TLS_ECP_ALT)
    "JHD_TLS_ECP_ALT",
#endif /* JHD_TLS_ECP_ALT */
#if defined(JHD_TLS_MD2_PROCESS_ALT)
    "JHD_TLS_MD2_PROCESS_ALT",
#endif /* JHD_TLS_MD2_PROCESS_ALT */
#if defined(JHD_TLS_MD4_PROCESS_ALT)
    "JHD_TLS_MD4_PROCESS_ALT",
#endif /* JHD_TLS_MD4_PROCESS_ALT */
#if defined(JHD_TLS_MD5_PROCESS_ALT)
    "JHD_TLS_MD5_PROCESS_ALT",
#endif /* JHD_TLS_MD5_PROCESS_ALT */
#if defined(JHD_TLS_RIPEMD160_PROCESS_ALT)
    "JHD_TLS_RIPEMD160_PROCESS_ALT",
#endif /* JHD_TLS_RIPEMD160_PROCESS_ALT */
#if defined(JHD_TLS_SHA1_PROCESS_ALT)
    "JHD_TLS_SHA1_PROCESS_ALT",
#endif /* JHD_TLS_SHA1_PROCESS_ALT */
#if defined(JHD_TLS_SHA256_PROCESS_ALT)
    "JHD_TLS_SHA256_PROCESS_ALT",
#endif /* JHD_TLS_SHA256_PROCESS_ALT */
#if defined(JHD_TLS_SHA512_PROCESS_ALT)
    "JHD_TLS_SHA512_PROCESS_ALT",
#endif /* JHD_TLS_SHA512_PROCESS_ALT */
#if defined(JHD_TLS_DES_SETKEY_ALT)
    "JHD_TLS_DES_SETKEY_ALT",
#endif /* JHD_TLS_DES_SETKEY_ALT */
#if defined(JHD_TLS_DES_CRYPT_ECB_ALT)
    "JHD_TLS_DES_CRYPT_ECB_ALT",
#endif /* JHD_TLS_DES_CRYPT_ECB_ALT */
#if defined(JHD_TLS_DES3_CRYPT_ECB_ALT)
    "JHD_TLS_DES3_CRYPT_ECB_ALT",
#endif /* JHD_TLS_DES3_CRYPT_ECB_ALT */
#if defined(JHD_TLS_AES_SETKEY_ENC_ALT)
    "JHD_TLS_AES_SETKEY_ENC_ALT",
#endif /* JHD_TLS_AES_SETKEY_ENC_ALT */
#if defined(JHD_TLS_AES_SETKEY_DEC_ALT)
    "JHD_TLS_AES_SETKEY_DEC_ALT",
#endif /* JHD_TLS_AES_SETKEY_DEC_ALT */
#if defined(JHD_TLS_AES_ENCRYPT_ALT)
    "JHD_TLS_AES_ENCRYPT_ALT",
#endif /* JHD_TLS_AES_ENCRYPT_ALT */
#if defined(JHD_TLS_AES_DECRYPT_ALT)
    "JHD_TLS_AES_DECRYPT_ALT",
#endif /* JHD_TLS_AES_DECRYPT_ALT */
#if defined(JHD_TLS_ECDH_GEN_PUBLIC_ALT)
    "JHD_TLS_ECDH_GEN_PUBLIC_ALT",
#endif /* JHD_TLS_ECDH_GEN_PUBLIC_ALT */
#if defined(JHD_TLS_ECDH_COMPUTE_SHARED_ALT)
    "JHD_TLS_ECDH_COMPUTE_SHARED_ALT",
#endif /* JHD_TLS_ECDH_COMPUTE_SHARED_ALT */
#if defined(JHD_TLS_ECDSA_VERIFY_ALT)
    "JHD_TLS_ECDSA_VERIFY_ALT",
#endif /* JHD_TLS_ECDSA_VERIFY_ALT */
#if defined(JHD_TLS_ECDSA_SIGN_ALT)
    "JHD_TLS_ECDSA_SIGN_ALT",
#endif /* JHD_TLS_ECDSA_SIGN_ALT */
#if defined(JHD_TLS_ECDSA_GENKEY_ALT)
    "JHD_TLS_ECDSA_GENKEY_ALT",
#endif /* JHD_TLS_ECDSA_GENKEY_ALT */
#if defined(JHD_TLS_ECP_INTERNAL_ALT)
    "JHD_TLS_ECP_INTERNAL_ALT",
#endif /* JHD_TLS_ECP_INTERNAL_ALT */
#if defined(JHD_TLS_ECP_RANDOMIZE_JAC_ALT)
    "JHD_TLS_ECP_RANDOMIZE_JAC_ALT",
#endif /* JHD_TLS_ECP_RANDOMIZE_JAC_ALT */
#if defined(JHD_TLS_ECP_ADD_MIXED_ALT)
    "JHD_TLS_ECP_ADD_MIXED_ALT",
#endif /* JHD_TLS_ECP_ADD_MIXED_ALT */
#if defined(JHD_TLS_ECP_DOUBLE_JAC_ALT)
    "JHD_TLS_ECP_DOUBLE_JAC_ALT",
#endif /* JHD_TLS_ECP_DOUBLE_JAC_ALT */
#if defined(JHD_TLS_ECP_NORMALIZE_JAC_MANY_ALT)
    "JHD_TLS_ECP_NORMALIZE_JAC_MANY_ALT",
#endif /* JHD_TLS_ECP_NORMALIZE_JAC_MANY_ALT */
#if defined(JHD_TLS_ECP_NORMALIZE_JAC_ALT)
    "JHD_TLS_ECP_NORMALIZE_JAC_ALT",
#endif /* JHD_TLS_ECP_NORMALIZE_JAC_ALT */
#if defined(JHD_TLS_ECP_DOUBLE_ADD_MXZ_ALT)
    "JHD_TLS_ECP_DOUBLE_ADD_MXZ_ALT",
#endif /* JHD_TLS_ECP_DOUBLE_ADD_MXZ_ALT */
#if defined(JHD_TLS_ECP_RANDOMIZE_MXZ_ALT)
    "JHD_TLS_ECP_RANDOMIZE_MXZ_ALT",
#endif /* JHD_TLS_ECP_RANDOMIZE_MXZ_ALT */
#if defined(JHD_TLS_ECP_NORMALIZE_MXZ_ALT)
    "JHD_TLS_ECP_NORMALIZE_MXZ_ALT",
#endif /* JHD_TLS_ECP_NORMALIZE_MXZ_ALT */
#if defined(JHD_TLS_TEST_NULL_ENTROPY)
    "JHD_TLS_TEST_NULL_ENTROPY",
#endif /* JHD_TLS_TEST_NULL_ENTROPY */
#if defined(JHD_TLS_ENTROPY_HARDWARE_ALT)
    "JHD_TLS_ENTROPY_HARDWARE_ALT",
#endif /* JHD_TLS_ENTROPY_HARDWARE_ALT */
#if defined(JHD_TLS_AES_ROM_TABLES)
    "JHD_TLS_AES_ROM_TABLES",
#endif /* JHD_TLS_AES_ROM_TABLES */
#if defined(JHD_TLS_AES_FEWER_TABLES)
    "JHD_TLS_AES_FEWER_TABLES",
#endif /* JHD_TLS_AES_FEWER_TABLES */
#if defined(JHD_TLS_CAMELLIA_SMALL_MEMORY)
    "JHD_TLS_CAMELLIA_SMALL_MEMORY",
#endif /* JHD_TLS_CAMELLIA_SMALL_MEMORY */
#if defined(JHD_TLS_CIPHER_MODE_CBC)
    "JHD_TLS_CIPHER_MODE_CBC",
#endif /* JHD_TLS_CIPHER_MODE_CBC */
#if defined(JHD_TLS_CIPHER_MODE_CFB)
    "JHD_TLS_CIPHER_MODE_CFB",
#endif /* JHD_TLS_CIPHER_MODE_CFB */
#if defined(JHD_TLS_CIPHER_MODE_CTR)
    "JHD_TLS_CIPHER_MODE_CTR",
#endif /* JHD_TLS_CIPHER_MODE_CTR */
#if defined(JHD_TLS_CIPHER_MODE_OFB)
    "JHD_TLS_CIPHER_MODE_OFB",
#endif /* JHD_TLS_CIPHER_MODE_OFB */
#if defined(JHD_TLS_CIPHER_MODE_XTS)
    "JHD_TLS_CIPHER_MODE_XTS",
#endif /* JHD_TLS_CIPHER_MODE_XTS */
#if defined(JHD_TLS_CIPHER_NULL_CIPHER)
    "JHD_TLS_CIPHER_NULL_CIPHER",
#endif /* JHD_TLS_CIPHER_NULL_CIPHER */
#if defined(JHD_TLS_CIPHER_PADDING_PKCS7)
    "JHD_TLS_CIPHER_PADDING_PKCS7",
#endif /* JHD_TLS_CIPHER_PADDING_PKCS7 */
#if defined(JHD_TLS_CIPHER_PADDING_ONE_AND_ZEROS)
    "JHD_TLS_CIPHER_PADDING_ONE_AND_ZEROS",
#endif /* JHD_TLS_CIPHER_PADDING_ONE_AND_ZEROS */
#if defined(JHD_TLS_CIPHER_PADDING_ZEROS_AND_LEN)
    "JHD_TLS_CIPHER_PADDING_ZEROS_AND_LEN",
#endif /* JHD_TLS_CIPHER_PADDING_ZEROS_AND_LEN */
#if defined(JHD_TLS_CIPHER_PADDING_ZEROS)
    "JHD_TLS_CIPHER_PADDING_ZEROS",
#endif /* JHD_TLS_CIPHER_PADDING_ZEROS */
#if defined(JHD_TLS_ENABLE_WEAK_CIPHERSUITES)
    "JHD_TLS_ENABLE_WEAK_CIPHERSUITES",
#endif /* JHD_TLS_ENABLE_WEAK_CIPHERSUITES */
#if defined(JHD_TLS_REMOVE_ARC4_CIPHERSUITES)
    "JHD_TLS_REMOVE_ARC4_CIPHERSUITES",
#endif /* JHD_TLS_REMOVE_ARC4_CIPHERSUITES */
#if defined(JHD_TLS_ECP_DP_SECP192R1_ENABLED)
    "JHD_TLS_ECP_DP_SECP192R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP192R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP224R1_ENABLED)
    "JHD_TLS_ECP_DP_SECP224R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP224R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP256R1_ENABLED)
    "JHD_TLS_ECP_DP_SECP256R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP256R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP384R1_ENABLED)
    "JHD_TLS_ECP_DP_SECP384R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP384R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP521R1_ENABLED)
    "JHD_TLS_ECP_DP_SECP521R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP521R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP192K1_ENABLED)
    "JHD_TLS_ECP_DP_SECP192K1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP192K1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP224K1_ENABLED)
    "JHD_TLS_ECP_DP_SECP224K1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP224K1_ENABLED */
#if defined(JHD_TLS_ECP_DP_SECP256K1_ENABLED)
    "JHD_TLS_ECP_DP_SECP256K1_ENABLED",
#endif /* JHD_TLS_ECP_DP_SECP256K1_ENABLED */
#if defined(JHD_TLS_ECP_DP_BP256R1_ENABLED)
    "JHD_TLS_ECP_DP_BP256R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_BP256R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_BP384R1_ENABLED)
    "JHD_TLS_ECP_DP_BP384R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_BP384R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_BP512R1_ENABLED)
    "JHD_TLS_ECP_DP_BP512R1_ENABLED",
#endif /* JHD_TLS_ECP_DP_BP512R1_ENABLED */
#if defined(JHD_TLS_ECP_DP_CURVE25519_ENABLED)
    "JHD_TLS_ECP_DP_CURVE25519_ENABLED",
#endif /* JHD_TLS_ECP_DP_CURVE25519_ENABLED */
#if defined(JHD_TLS_ECP_DP_CURVE448_ENABLED)
    "JHD_TLS_ECP_DP_CURVE448_ENABLED",
#endif /* JHD_TLS_ECP_DP_CURVE448_ENABLED */
#if defined(JHD_TLS_ECP_NIST_OPTIM)
    "JHD_TLS_ECP_NIST_OPTIM",
#endif /* JHD_TLS_ECP_NIST_OPTIM */
#if defined(JHD_TLS_ECDSA_DETERMINISTIC)
    "JHD_TLS_ECDSA_DETERMINISTIC",
#endif /* JHD_TLS_ECDSA_DETERMINISTIC */
#if defined(JHD_TLS_KEY_EXCHANGE_PSK_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_PSK_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_PSK_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_DHE_PSK_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_DHE_PSK_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_DHE_PSK_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_RSA_PSK_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_RSA_PSK_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_RSA_PSK_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_RSA_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_RSA_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_RSA_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_DHE_RSA_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_DHE_RSA_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_DHE_RSA_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_ECDH_RSA_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_ECDH_RSA_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_ECDH_RSA_ENABLED */
#if defined(JHD_TLS_KEY_EXCHANGE_ECJPAKE_ENABLED)
    "JHD_TLS_KEY_EXCHANGE_ECJPAKE_ENABLED",
#endif /* JHD_TLS_KEY_EXCHANGE_ECJPAKE_ENABLED */
#if defined(JHD_TLS_PK_PARSE_EC_EXTENDED)
    "JHD_TLS_PK_PARSE_EC_EXTENDED",
#endif /* JHD_TLS_PK_PARSE_EC_EXTENDED */
#if defined(JHD_TLS_ERROR_STRERROR_DUMMY)
    "JHD_TLS_ERROR_STRERROR_DUMMY",
#endif /* JHD_TLS_ERROR_STRERROR_DUMMY */
#if defined(JHD_TLS_GENPRIME)
    "JHD_TLS_GENPRIME",
#endif /* JHD_TLS_GENPRIME */
#if defined(JHD_TLS_FS_IO)
    "JHD_TLS_FS_IO",
#endif /* JHD_TLS_FS_IO */
#if defined(JHD_TLS_NO_DEFAULT_ENTROPY_SOURCES)
    "JHD_TLS_NO_DEFAULT_ENTROPY_SOURCES",
#endif /* JHD_TLS_NO_DEFAULT_ENTROPY_SOURCES */
#if defined(JHD_TLS_NO_PLATFORM_ENTROPY)
    "JHD_TLS_NO_PLATFORM_ENTROPY",
#endif /* JHD_TLS_NO_PLATFORM_ENTROPY */
#if defined(JHD_TLS_ENTROPY_FORCE_SHA256)
    "JHD_TLS_ENTROPY_FORCE_SHA256",
#endif /* JHD_TLS_ENTROPY_FORCE_SHA256 */
#if defined(JHD_TLS_ENTROPY_NV_SEED)
    "JHD_TLS_ENTROPY_NV_SEED",
#endif /* JHD_TLS_ENTROPY_NV_SEED */
#if defined(JHD_TLS_MEMORY_DEBUG)
    "JHD_TLS_MEMORY_DEBUG",
#endif /* JHD_TLS_MEMORY_DEBUG */
#if defined(JHD_TLS_MEMORY_BACKTRACE)
    "JHD_TLS_MEMORY_BACKTRACE",
#endif /* JHD_TLS_MEMORY_BACKTRACE */
#if defined(JHD_TLS_PK_RSA_ALT_SUPPORT)
    "JHD_TLS_PK_RSA_ALT_SUPPORT",
#endif /* JHD_TLS_PK_RSA_ALT_SUPPORT */
#if defined(JHD_TLS_PKCS1_V15)
    "JHD_TLS_PKCS1_V15",
#endif /* JHD_TLS_PKCS1_V15 */
#if defined(JHD_TLS_PKCS1_V21)
    "JHD_TLS_PKCS1_V21",
#endif /* JHD_TLS_PKCS1_V21 */
#if defined(JHD_TLS_RSA_NO_CRT)
    "JHD_TLS_RSA_NO_CRT",
#endif /* JHD_TLS_RSA_NO_CRT */
#if defined(JHD_TLS_SELF_TEST)
    "JHD_TLS_SELF_TEST",
#endif /* JHD_TLS_SELF_TEST */
#if defined(JHD_TLS_SHA256_SMALLER)
    "JHD_TLS_SHA256_SMALLER",
#endif /* JHD_TLS_SHA256_SMALLER */
#if defined(JHD_TLS_SSL_ALL_ALERT_MESSAGES)
    "JHD_TLS_SSL_ALL_ALERT_MESSAGES",
#endif /* JHD_TLS_SSL_ALL_ALERT_MESSAGES */
#if defined(JHD_TLS_SSL_ASYNC_PRIVATE)
    "JHD_TLS_SSL_ASYNC_PRIVATE",
#endif /* JHD_TLS_SSL_ASYNC_PRIVATE */
#if defined(JHD_TLS_SSL_DEBUG_ALL)
    "JHD_TLS_SSL_DEBUG_ALL",
#endif /* JHD_TLS_SSL_DEBUG_ALL */
#if defined(JHD_TLS_SSL_ENCRYPT_THEN_MAC)
    "JHD_TLS_SSL_ENCRYPT_THEN_MAC",
#endif /* JHD_TLS_SSL_ENCRYPT_THEN_MAC */
#if defined(JHD_TLS_SSL_EXTENDED_MASTER_SECRET)
    "JHD_TLS_SSL_EXTENDED_MASTER_SECRET",
#endif /* JHD_TLS_SSL_EXTENDED_MASTER_SECRET */
#if defined(JHD_TLS_SSL_FALLBACK_SCSV)
    "JHD_TLS_SSL_FALLBACK_SCSV",
#endif /* JHD_TLS_SSL_FALLBACK_SCSV */
#if defined(JHD_TLS_SSL_HW_RECORD_ACCEL)
    "JHD_TLS_SSL_HW_RECORD_ACCEL",
#endif /* JHD_TLS_SSL_HW_RECORD_ACCEL */
#if defined(JHD_TLS_SSL_CBC_RECORD_SPLITTING)
    "JHD_TLS_SSL_CBC_RECORD_SPLITTING",
#endif /* JHD_TLS_SSL_CBC_RECORD_SPLITTING */
#if defined(JHD_TLS_SSL_RENEGOTIATION)
    "JHD_TLS_SSL_RENEGOTIATION",
#endif /* JHD_TLS_SSL_RENEGOTIATION */
#if defined(JHD_TLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO)
    "JHD_TLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO",
#endif /* JHD_TLS_SSL_SRV_SUPPORT_SSLV2_CLIENT_HELLO */
#if defined(JHD_TLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE)
    "JHD_TLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE",
#endif /* JHD_TLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE */
#if defined(JHD_TLS_SSL_MAX_FRAGMENT_LENGTH)
    "JHD_TLS_SSL_MAX_FRAGMENT_LENGTH",
#endif /* JHD_TLS_SSL_MAX_FRAGMENT_LENGTH */
#if defined(JHD_TLS_SSL_PROTO_SSL3)
    "JHD_TLS_SSL_PROTO_SSL3",
#endif /* JHD_TLS_SSL_PROTO_SSL3 */
#if defined(JHD_TLS_SSL_PROTO_TLS1)
    "JHD_TLS_SSL_PROTO_TLS1",
#endif /* JHD_TLS_SSL_PROTO_TLS1 */
#if defined(JHD_TLS_SSL_PROTO_TLS1_1)
    "JHD_TLS_SSL_PROTO_TLS1_1",
#endif /* JHD_TLS_SSL_PROTO_TLS1_1 */
#if defined(JHD_TLS_SSL_PROTO_TLS1_2)
    "JHD_TLS_SSL_PROTO_TLS1_2",
#endif /* JHD_TLS_SSL_PROTO_TLS1_2 */
#if defined(JHD_TLS_SSL_PROTO_DTLS)
    "JHD_TLS_SSL_PROTO_DTLS",
#endif /* JHD_TLS_SSL_PROTO_DTLS */
#if defined(JHD_TLS_SSL_ALPN)
    "JHD_TLS_SSL_ALPN",
#endif /* JHD_TLS_SSL_ALPN */
#if defined(JHD_TLS_SSL_DTLS_ANTI_REPLAY)
    "JHD_TLS_SSL_DTLS_ANTI_REPLAY",
#endif /* JHD_TLS_SSL_DTLS_ANTI_REPLAY */
#if defined(JHD_TLS_SSL_DTLS_HELLO_VERIFY)
    "JHD_TLS_SSL_DTLS_HELLO_VERIFY",
#endif /* JHD_TLS_SSL_DTLS_HELLO_VERIFY */
#if defined(JHD_TLS_SSL_DTLS_CLIENT_PORT_REUSE)
    "JHD_TLS_SSL_DTLS_CLIENT_PORT_REUSE",
#endif /* JHD_TLS_SSL_DTLS_CLIENT_PORT_REUSE */
#if defined(JHD_TLS_SSL_DTLS_BADMAC_LIMIT)
    "JHD_TLS_SSL_DTLS_BADMAC_LIMIT",
#endif /* JHD_TLS_SSL_DTLS_BADMAC_LIMIT */
#if defined(JHD_TLS_SSL_SESSION_TICKETS)
    "JHD_TLS_SSL_SESSION_TICKETS",
#endif /* JHD_TLS_SSL_SESSION_TICKETS */
#if defined(JHD_TLS_SSL_EXPORT_KEYS)
    "JHD_TLS_SSL_EXPORT_KEYS",
#endif /* JHD_TLS_SSL_EXPORT_KEYS */
#if defined(JHD_TLS_SSL_SERVER_NAME_INDICATION)
    "JHD_TLS_SSL_SERVER_NAME_INDICATION",
#endif /* JHD_TLS_SSL_SERVER_NAME_INDICATION */
#if defined(JHD_TLS_SSL_TRUNCATED_HMAC)
    "JHD_TLS_SSL_TRUNCATED_HMAC",
#endif /* JHD_TLS_SSL_TRUNCATED_HMAC */
#if defined(JHD_TLS_SSL_TRUNCATED_HMAC_COMPAT)
    "JHD_TLS_SSL_TRUNCATED_HMAC_COMPAT",
#endif /* JHD_TLS_SSL_TRUNCATED_HMAC_COMPAT */
#if defined(JHD_TLS_THREADING_ALT)
    "JHD_TLS_THREADING_ALT",
#endif /* JHD_TLS_THREADING_ALT */
#if defined(JHD_TLS_THREADING_PTHREAD)
    "JHD_TLS_THREADING_PTHREAD",
#endif /* JHD_TLS_THREADING_PTHREAD */
#if defined(JHD_TLS_VERSION_FEATURES)
    "JHD_TLS_VERSION_FEATURES",
#endif /* JHD_TLS_VERSION_FEATURES */
#if defined(JHD_TLS_X509_ALLOW_EXTENSIONS_NON_V3)
    "JHD_TLS_X509_ALLOW_EXTENSIONS_NON_V3",
#endif /* JHD_TLS_X509_ALLOW_EXTENSIONS_NON_V3 */
#if defined(JHD_TLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION)
    "JHD_TLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION",
#endif /* JHD_TLS_X509_ALLOW_UNSUPPORTED_CRITICAL_EXTENSION */
#if defined(JHD_TLS_X509_CHECK_KEY_USAGE)
    "JHD_TLS_X509_CHECK_KEY_USAGE",
#endif /* JHD_TLS_X509_CHECK_KEY_USAGE */
#if defined(JHD_TLS_X509_CHECK_EXTENDED_KEY_USAGE)
    "JHD_TLS_X509_CHECK_EXTENDED_KEY_USAGE",
#endif /* JHD_TLS_X509_CHECK_EXTENDED_KEY_USAGE */
#if defined(JHD_TLS_X509_RSASSA_PSS_SUPPORT)
    "JHD_TLS_X509_RSASSA_PSS_SUPPORT",
#endif /* JHD_TLS_X509_RSASSA_PSS_SUPPORT */
#if defined(JHD_TLS_ZLIB_SUPPORT)
    "JHD_TLS_ZLIB_SUPPORT",
#endif /* JHD_TLS_ZLIB_SUPPORT */
#if defined(JHD_TLS_AESNI_C)
    "JHD_TLS_AESNI_C",
#endif /* JHD_TLS_AESNI_C */
#if defined(JHD_TLS_AES_C)
    "JHD_TLS_AES_C",
#endif /* JHD_TLS_AES_C */
#if defined(JHD_TLS_ARC4_C)
    "JHD_TLS_ARC4_C",
#endif /* JHD_TLS_ARC4_C */
#if defined(JHD_TLS_ASN1_PARSE_C)
    "JHD_TLS_ASN1_PARSE_C",
#endif /* JHD_TLS_ASN1_PARSE_C */
#if defined(JHD_TLS_ASN1_WRITE_C)
    "JHD_TLS_ASN1_WRITE_C",
#endif /* JHD_TLS_ASN1_WRITE_C */
#if defined(JHD_TLS_BASE64_C)
    "JHD_TLS_BASE64_C",
#endif /* JHD_TLS_BASE64_C */
#if defined(JHD_TLS_BIGNUM_C)
    "JHD_TLS_BIGNUM_C",
#endif /* JHD_TLS_BIGNUM_C */
#if defined(JHD_TLS_BLOWFISH_C)
    "JHD_TLS_BLOWFISH_C",
#endif /* JHD_TLS_BLOWFISH_C */
#if defined(JHD_TLS_CAMELLIA_C)
    "JHD_TLS_CAMELLIA_C",
#endif /* JHD_TLS_CAMELLIA_C */
#if defined(JHD_TLS_ARIA_C)
    "JHD_TLS_ARIA_C",
#endif /* JHD_TLS_ARIA_C */
#if defined(JHD_TLS_CCM_C)
    "JHD_TLS_CCM_C",
#endif /* JHD_TLS_CCM_C */
#if defined(JHD_TLS_CERTS_C)
    "JHD_TLS_CERTS_C",
#endif /* JHD_TLS_CERTS_C */
#if defined(JHD_TLS_CIPHER_C)
    "JHD_TLS_CIPHER_C",
#endif /* JHD_TLS_CIPHER_C */
#if defined(JHD_TLS_CMAC_C)
    "JHD_TLS_CMAC_C",
#endif /* JHD_TLS_CMAC_C */
#if defined(JHD_TLS_CTR_DRBG_C)
    "JHD_TLS_CTR_DRBG_C",
#endif /* JHD_TLS_CTR_DRBG_C */
#if defined(JHD_TLS_DEBUG_C)
    "JHD_TLS_DEBUG_C",
#endif /* JHD_TLS_DEBUG_C */
#if defined(JHD_TLS_DES_C)
    "JHD_TLS_DES_C",
#endif /* JHD_TLS_DES_C */
#if defined(JHD_TLS_DHM_C)
    "JHD_TLS_DHM_C",
#endif /* JHD_TLS_DHM_C */
#if defined(JHD_TLS_ECDH_C)
    "JHD_TLS_ECDH_C",
#endif /* JHD_TLS_ECDH_C */
#if defined(JHD_TLS_ECDSA_C)
    "JHD_TLS_ECDSA_C",
#endif /* JHD_TLS_ECDSA_C */
#if defined(JHD_TLS_ECJPAKE_C)
    "JHD_TLS_ECJPAKE_C",
#endif /* JHD_TLS_ECJPAKE_C */
#if defined(JHD_TLS_ECP_C)
    "JHD_TLS_ECP_C",
#endif /* JHD_TLS_ECP_C */
#if defined(JHD_TLS_ENTROPY_C)
    "JHD_TLS_ENTROPY_C",
#endif /* JHD_TLS_ENTROPY_C */
#if defined(JHD_TLS_ERROR_C)
    "JHD_TLS_ERROR_C",
#endif /* JHD_TLS_ERROR_C */
#if defined(JHD_TLS_GCM_C)
    "JHD_TLS_GCM_C",
#endif /* JHD_TLS_GCM_C */
#if defined(JHD_TLS_HAVEGE_C)
    "JHD_TLS_HAVEGE_C",
#endif /* JHD_TLS_HAVEGE_C */
#if defined(JHD_TLS_HKDF_C)
    "JHD_TLS_HKDF_C",
#endif /* JHD_TLS_HKDF_C */
#if defined(JHD_TLS_HMAC_DRBG_C)
    "JHD_TLS_HMAC_DRBG_C",
#endif /* JHD_TLS_HMAC_DRBG_C */
#if defined(JHD_TLS_MD_C)
    "JHD_TLS_MD_C",
#endif /* JHD_TLS_MD_C */
#if defined(JHD_TLS_MD2_C)
    "JHD_TLS_MD2_C",
#endif /* JHD_TLS_MD2_C */
#if defined(JHD_TLS_MD4_C)
    "JHD_TLS_MD4_C",
#endif /* JHD_TLS_MD4_C */
#if defined(JHD_TLS_MD5_C)
    "JHD_TLS_MD5_C",
#endif /* JHD_TLS_MD5_C */
#if defined(JHD_TLS_MEMORY_BUFFER_ALLOC_C)
    "JHD_TLS_MEMORY_BUFFER_ALLOC_C",
#endif /* JHD_TLS_MEMORY_BUFFER_ALLOC_C */
#if defined(JHD_TLS_NET_C)
    "JHD_TLS_NET_C",
#endif /* JHD_TLS_NET_C */
#if defined(JHD_TLS_OID_C)
    "JHD_TLS_OID_C",
#endif /* JHD_TLS_OID_C */
#if defined(JHD_TLS_PADLOCK_C)
    "JHD_TLS_PADLOCK_C",
#endif /* JHD_TLS_PADLOCK_C */
#if defined(JHD_TLS_PEM_PARSE_C)
    "JHD_TLS_PEM_PARSE_C",
#endif /* JHD_TLS_PEM_PARSE_C */
#if defined(JHD_TLS_PEM_WRITE_C)
    "JHD_TLS_PEM_WRITE_C",
#endif /* JHD_TLS_PEM_WRITE_C */
#if defined(JHD_TLS_PK_C)
    "JHD_TLS_PK_C",
#endif /* JHD_TLS_PK_C */
#if defined(JHD_TLS_PK_PARSE_C)
    "JHD_TLS_PK_PARSE_C",
#endif /* JHD_TLS_PK_PARSE_C */
#if defined(JHD_TLS_PK_WRITE_C)
    "JHD_TLS_PK_WRITE_C",
#endif /* JHD_TLS_PK_WRITE_C */
#if defined(JHD_TLS_PKCS5_C)
    "JHD_TLS_PKCS5_C",
#endif /* JHD_TLS_PKCS5_C */
#if defined(JHD_TLS_PKCS11_C)
    "JHD_TLS_PKCS11_C",
#endif /* JHD_TLS_PKCS11_C */
#if defined(JHD_TLS_PKCS12_C)
    "JHD_TLS_PKCS12_C",
#endif /* JHD_TLS_PKCS12_C */
#if defined(JHD_TLS_PLATFORM_C)
    "JHD_TLS_PLATFORM_C",
#endif /* JHD_TLS_PLATFORM_C */
#if defined(JHD_TLS_RIPEMD160_C)
    "JHD_TLS_RIPEMD160_C",
#endif /* JHD_TLS_RIPEMD160_C */
#if defined(JHD_TLS_RSA_C)
    "JHD_TLS_RSA_C",
#endif /* JHD_TLS_RSA_C */
#if defined(JHD_TLS_SHA1_C)
    "JHD_TLS_SHA1_C",
#endif /* JHD_TLS_SHA1_C */
#if defined(JHD_TLS_SHA256_C)
    "JHD_TLS_SHA256_C",
#endif /* JHD_TLS_SHA256_C */
#if defined(JHD_TLS_SHA512_C)
    "JHD_TLS_SHA512_C",
#endif /* JHD_TLS_SHA512_C */
#if defined(JHD_TLS_SSL_CACHE_C)
    "JHD_TLS_SSL_CACHE_C",
#endif /* JHD_TLS_SSL_CACHE_C */
#if defined(JHD_TLS_SSL_COOKIE_C)
    "JHD_TLS_SSL_COOKIE_C",
#endif /* JHD_TLS_SSL_COOKIE_C */
#if defined(JHD_TLS_SSL_TICKET_C)
    "JHD_TLS_SSL_TICKET_C",
#endif /* JHD_TLS_SSL_TICKET_C */
#if defined(JHD_TLS_SSL_CLI_C)
    "JHD_TLS_SSL_CLI_C",
#endif /* JHD_TLS_SSL_CLI_C */
#if defined(JHD_TLS_SSL_SRV_C)
    "JHD_TLS_SSL_SRV_C",
#endif /* JHD_TLS_SSL_SRV_C */
#if defined(JHD_TLS_SSL_TLS_C)
    "JHD_TLS_SSL_TLS_C",
#endif /* JHD_TLS_SSL_TLS_C */
#if defined(JHD_TLS_THREADING_C)
    "JHD_TLS_THREADING_C",
#endif /* JHD_TLS_THREADING_C */
#if defined(JHD_TLS_TIMING_C)
    "JHD_TLS_TIMING_C",
#endif /* JHD_TLS_TIMING_C */
#if defined(JHD_TLS_VERSION_C)
    "JHD_TLS_VERSION_C",
#endif /* JHD_TLS_VERSION_C */
#if defined(JHD_TLS_X509_USE_C)
    "JHD_TLS_X509_USE_C",
#endif /* JHD_TLS_X509_USE_C */
#if defined(JHD_TLS_X509_CRT_PARSE_C)
    "JHD_TLS_X509_CRT_PARSE_C",
#endif /* JHD_TLS_X509_CRT_PARSE_C */
#if defined(JHD_TLS_X509_CRL_PARSE_C)
    "JHD_TLS_X509_CRL_PARSE_C",
#endif /* JHD_TLS_X509_CRL_PARSE_C */
#if defined(JHD_TLS_X509_CSR_PARSE_C)
    "JHD_TLS_X509_CSR_PARSE_C",
#endif /* JHD_TLS_X509_CSR_PARSE_C */
#if defined(JHD_TLS_X509_CREATE_C)
    "JHD_TLS_X509_CREATE_C",
#endif /* JHD_TLS_X509_CREATE_C */
#if defined(JHD_TLS_X509_CRT_WRITE_C)
    "JHD_TLS_X509_CRT_WRITE_C",
#endif /* JHD_TLS_X509_CRT_WRITE_C */
#if defined(JHD_TLS_X509_CSR_WRITE_C)
    "JHD_TLS_X509_CSR_WRITE_C",
#endif /* JHD_TLS_X509_CSR_WRITE_C */
#if defined(JHD_TLS_XTEA_C)
    "JHD_TLS_XTEA_C",
#endif /* JHD_TLS_XTEA_C */
#endif /* JHD_TLS_VERSION_FEATURES */
    NULL
};

int jhd_tls_version_check_feature( const char *feature )
{
    const char **idx = features;

    if( *idx == NULL )
        return( -2 );

    if( feature == NULL )
        return( -1 );

    while( *idx != NULL )
    {
        if( !strcmp( *idx, feature ) )
            return( 0 );
        idx++;
    }
    return( -1 );
}

#endif /* JHD_TLS_VERSION_C */
